#!/usr/bin/env python3
"""Copy assets/style.css and assets/viz.js into every page, so each HTML file works on its own.

Run from the algorithms/ folder after editing anything in assets/:

    python3 tools/inline_assets.py          # rewrite the pages
    python3 tools/inline_assets.py --check  # exit 1 if any page is out of date (no writes)

Each page keeps its copy between the markers
    <!-- inline-assets:start ... -->  and  <!-- inline-assets:end -->
"""
import glob
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
START = "<!-- inline-assets:start (generated by tools/inline_assets.py from assets/) -->"
END = "<!-- inline-assets:end -->"


def block():
    with open(os.path.join(ROOT, "assets", "style.css"), encoding="utf-8") as f:
        css = f.read()
    with open(os.path.join(ROOT, "assets", "viz.js"), encoding="utf-8") as f:
        js = f.read()
    return f"{START}\n<style>\n{css.rstrip()}\n\n</style>\n<script>\n{js.rstrip()}\n</script>\n{END}"


def pages():
    names = ["index.html", "cheatsheet.html"] + sorted(glob.glob(os.path.join("patterns", "*.html")))
    return [os.path.join(ROOT, n) for n in names]


def main():
    check = "--check" in sys.argv
    new_block = block()
    stale = []
    for path in pages():
        with open(path, encoding="utf-8") as f:
            html = f.read()
        a = html.find(START)
        b = html.find(END)
        if a < 0 or b < 0:
            sys.exit(f"{os.path.relpath(path, ROOT)}: inline-assets markers not found")
        updated = html[:a] + new_block + html[b + len(END):]
        if updated != html:
            stale.append(os.path.relpath(path, ROOT))
            if not check:
                with open(path, "w", encoding="utf-8") as f:
                    f.write(updated)
    if check:
        print("out of date: " + ", ".join(stale) if stale else "all pages up to date")
        sys.exit(1 if stale else 0)
    print(f"updated {len(stale)} page(s)" if stale else "all pages already up to date")


if __name__ == "__main__":
    main()
